### ISSUE TITLE
Feed articles points to URL of the feed itself

### ISSUE THREAD

**Issue by miso-belica** [feedbin/feedbin#330]
Hi, I am subscribed to the following feed https://devblogy.k47.cz/rss.xml and items are shown as usual but when I click to the header to open the article I open the URL of the RSS feed instead of the article. I can see there is a correct link in the XML and I tried other 2 RSS readers and they work OK. Can you please fix it in the Feedbin?

**Comment by benubois** [comment]
Hi @miso-belica,

I identified an issue in Feedbin's RSS parser that prevents parsing this type of link. I've [submitted a patch](https://github.com/feedjira/feedjira/pull/420) for it to be fixed upstream and it should makes its way to Feedbin soon.

Thanks for reporting this!

Ben

**Comment by miso-belica** [comment]
@benubois I don't want to rude or something because I am really thankful you prepared the fix, but is it possible to finish this anytime soon, please? The issue is pretty annoying and when I see the fix is basically done and all it needs is to solve conflicts and deploy it's even more sad to me :(

**Comment by benubois** [comment]
Sorry! I had forgotten about this. I’ve updated the pull request.

**Comment by miso-belica** [comment]
@benubois is it already deployed? Because I have still the same issue :(

**Comment by miso-belica** [comment]
Pretty please 😞

**Comment by miso-belica** [comment]
I moved to [Inoreader](https://www.inoreader.com/) a long time ago. Their support solve the problems of the customers fast 🙂
